### ISSUE TITLE
CoreAudio Sample Projects 다운로드 정보

### ISSUE THREAD

**Issue by iOHS** [iOHS/CoreAudio-Sample#1]
Sample Project Path (에어콘 출판사 : iOS 코어 오디오 프로그래밍 [녹음, 재생, 변환에서 위치기반 음향까지 오디오 앱 개발], http://www.acornpub.co.kr/book/ios-core-audio)

**Comment by Ohsw** [comment]
댓글

**Comment by iOHS** [comment]
다운로드 정보 공유 완료.
